---
#  docker run -it --name wordpress-sqlite --rm -p 9000:9000 -v ./wp-content:/app/wp-content liguana/wordpress-sqlite
name: wordpress

services:
  wordpress-sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    image: liguana/wordpress-sqlite
    container_name: wordpress
    hostname: wordpress
    expose:
      - 8000
    volumes:
      - ./wp-content/database:/app/wp-content/database
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./wp-content/plugins:/app/wp-content/plugins
      - ./wp-content/themes:/app/wp-content/themes
      - ./wordpress/wp-config.php:/app/wp-config.php:ro
    restart: unless-stopped

networks:
  default:
    name: npm
    external: true
