---
#  docker run -it --name wordpress-sqlite --rm -p 9000:9000 -v ./wp-content:/app/wp-content liguana/wordpress-sqlite
name: wordpress

services:
  wordpress-sqlite:
    build:
      context: .
      dockerfile: Dockerfile
    image: liguana/wordpress-sqlite
    container_name: wordpress
    hostname: wordpress
    expose:
      - 9000
    volumes:
      - ./wp-content:/app/wp-content
    restart: unless-stopped

networks:
  default:
    name: npm
    external: true
