---
#  docker run -it --name wp-sqlite --rm -p 8000:8000 -v /tmp:/tmp registry.liguana.cl/wp-sqlite:7.1
name: wordpress

services:
  wordpress:
    image: registry.liguana.cl/wp-sqlite:7.1
    container_name: wordpress
    hostname: wordpress
    expose:
      - 8000
    volumes:
      - ./wp-content/database:/app/wp-content/database
      - ./wp-content/uploads:/app/wp-content/uploads
      - ./wp-content/plugins:/app/wp-content/plugins
      - ./wp-content/themes:/app/wp-content/themes
      - ./wordpress/wp-config.php:/app/wp-config.php:ro
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: wordpress-redis
    hostname: wordpress-redis
    command: redis-server --save "" --appendonly no
    expose:
      - 6379
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3

networks:
  default:
    name: npm
    external: true
